/*pokemon 1*/
INSERT INTO `pokemons` (`id`,`name`,`description`,`height`, `weight`,`code`, `image`) VALUES (NULL, 'pichu','Pichu está basado en un roedor. Pichu tiene una piel de color amarillo pálido, con las mejillas rosadas, una cola corta negra y orejas grandes, con bordeados de color negro. Su pequeño tamaño puede despistar a cualquier entrenador novato, pero puede paralizar incluso a humanos adultos si no se tiene cuidado.','1.00', '4.4', '#0172','pichu.png')

INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 1, 'pikachu','Pikachu es un pequeño Pokémon cuya morfología se encuentra basada en un roedor. Aunque su nombre y su categoría hagan alusión a un ratón, según su diseñadora, sus mejillas están basadas en las de una ardilla. Su cuerpo es de color amarillo con dos rayas marrones en su espalda y en la base de la cola. La punta de sus orejas de color negro, y presenta un gran círculo rojo en cada una de sus mejillas. Tiene una cola con forma de rayo si es macho y en forma de corazón si es hembra.', '1.04', '13.2','#0025','pikachu.png')
INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 1, 'raichu','Este Pokémon es un gran roedor bípedo. Tiene un pelaje anaranjado, una cola oscura y gruesa como un cable de tendido eléctrico que termina en forma de rayo y totalmente plano, que además puede soportar grandes cargas.','2.07', '66.1', '#0026', 'raichu.png')

/*pokemon 2*/
INSERT INTO `pokemons` (`id`,`name`,`description`,`height`, `weight`,`code`, `image`) VALUES (NULL, 'bulbasaur', 'Bulbasaur es un Pokémon de tipo planta y veneno. Es conocido por tener una planta en su espalda que crecerá a medida que evoluciona. Tiene un cuerpo de color verde y unas manchas más oscuras en su piel. Es pequeño pero muy fuerte y ágil, y a menudo es considerado un excelente compañero por los entrenadores.', '2.04', '15.2','#0001','bulbasaur.png');

INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 2, 'ivysaur', 'Ivysaur es la evolución de Bulbasaur y es de tipo planta y veneno. Tiene una planta más grande que bulbasaur en su espalda, y su cuerpo se ha vuelto un poco más robusto. Ivysaur es conocido por tener un temperamento más fuerte y un poder más notable en batalla.', '3.03', '28.7', '#0002', 'ivysaur.png');
INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 2, 'venusaur', 'Venusaur es la forma final de Bulbasaur. Se ha convertido en un Pokémon considerablemente más grande, con una enorme planta en su espalda que ha florecido en una hermosa flor. Venusaur es poderoso y capaz de controlar el entorno a su alrededor a través de sus habilidades de tipo planta.', '6.07', '220.5', '#0003', 'venusaur.png');

/*pokemon 3*/
INSERT INTO `pokemons` (`id`,`name`,`description`,`height`, `weight`,`code`, `image`) VALUES (NULL, 'charmander', 'Charmander es un Pokémon de tipo fuego. Su cuerpo es de color naranja y tiene una llama en la punta de su cola que muestra su estado emocional y salud. Charmander es un Pokémon popular y adora la luz y el calor, lo que le permite crecer en uno de los Pokémon más poderosos si evoluciona correctamente.', '2.00', '18.7','#0004','charmander.png');

INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 3, 'charmeleon', 'Charmeleon es la evolución de Charmander. Se distingue por su temperamento más feroz y su capacidad para controlar mejor el fuego, lo que le hace un adversario formidable en batalla. Su cola sigue ardiendo intensamente, y se vuelve más poderoso al crecer.', '3.07', '41.9', '#0005', 'charmeleon.png');
INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 3, 'charizard', 'Charizard es la evolución final de Charmander. Es un Pokémon de tipo fuego y volador, con la capacidad de volar a altas altitudes. Su cuerpo ha crecido significativamente y sus alas son fuertes y poderosas, lo que le permite lanzar potentes ataques de fuego.', '5.07', '199.5', '#0006', 'charizard.png');

/*pokemon 4*/
INSERT INTO `pokemons` (`id`,`name`,`description`,`height`, `weight`,`code`, `image`) VALUES (NULL, 'squirtle', 'Squirtle es un Pokémon de tipo agua que se asemeja a una pequeña tortuga. Es conocido por su caparazón duro y su adorable apariencia. Squirtle es ingenioso y muy hábil en el uso del agua, siendo un compañero confiable para los entrenadores.', '1.08', '19.8','#0007','squirtle.png');

INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 4, 'wartortle', 'Wartortle es la evolución de Squirtle y presenta orejas más largas y un pelaje más esponjoso. Es conocido por su gran agilidad y sus habilidades en batalla, además de su capacidad para manipular el agua con gran eficacia.', '3.03', '49.6', '#0008', 'wartortle.png');
INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 4, 'blastoise', 'Blastoise es la forma final de Squirtle. Este Pokémon es imponente, con un caparazón resistente y dos cañones de agua en su espalda. Blastoise puede lanzar poderosos chorros de agua, lo que lo convierte en un formidable Pokémon en combate.', '5.03', '188.5', '#0009', 'blastoise.png');

/*pokemon 5*/
INSERT INTO `pokemons` (`id`,`name`,`description`,`height`, `weight`,`code`, `image`) VALUES (NULL, 'caterpie', 'Caterpie es un Pokémon de tipo bicho que se asemeja a una oruga. Es conocido por ser uno de los Pokémon más débiles pero también uno de los más abundantes. Su cuerpo es de un verde brillante, y tiene grandes ojos que le permiten ver en todas direcciones.', '1.00', '6.4','#0010','caterpie.png');

INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 5, 'metapod', 'Metapod es la evolución de Caterpie. Su cuerpo se transforma en una cápsula duradera, y aunque no tiene mucha capacidad de movimiento o ataque, es fuerte defensivamente y está en proceso de convertirse en un Pokémon más potente.', '2.04', '21.8', '#0011', 'metapod.png');
INSERT INTO `evolutions` (`id`, `pokemon_id`, `name`,`description`,`height`, `weight`, `code` ,`image`) VALUES (NULL, 5, 'butterfree', 'Butterfree es la forma final de Caterpie. Es un hermoso Pokémon de tipo bicho y volador con grandes alas que le permiten volar y libar néctar de las flores. Butterfree es considerado un Pokémon muy elegante y es conocido por sus habilidades en batalla.', '3.07', '70.5', '#0012', 'butterfree.png');
